CREATE 	TABLE AUTHOR (
	AUTHOR_ID		NUMBER(10)				,
	AUTHOR_NAME		VARCHAR2(100)	NOT NULL,
	AUTHOR_DESC		VARCHAR2(500)			,
	PRIMARY KEY(AUTHOR_ID)
);
COMMIT;

INSERT INTO AUTHOR 
VALUES (1, '박경리', '토지 작가 ' );

INSERT INTO author( author_id, author_name )
VALUES (2, '이문열' );

COMMIT;

UPDATE 	AUTHOR
SET 	AUTHOR_NAME = '기안84'	, 
		AUTHOR_DESC = '웹툰작가' 
WHERE 	AUTHOR_ID = 1 ;

UPDATE 	AUTHOR
SET 	AUTHOR_NAME = '강풀'	, 
		AUTHOR_DESC = '인기작가' ;
	
DELETE FROM AUTHOR;
COMMIT;

SELECT * FROM AUTHOR;

DROP 	SEQUENCE SEQ_AUTHOR_ID;
CREATE 	SEQUENCE SEQ_AUTHOR_ID
INCREMENT BY 	1
START WITH		1;

INSERT INTO AUTHOR 
VALUES (SEQ_AUTHOR_ID.NEXTVAL, '박경리', '토지 작가');

INSERT INTO AUTHOR 
VALUES (SEQ_AUTHOR_ID.NEXTVAL, '이문열', '삼국지 작가');

INSERT INTO AUTHOR 
VALUES (SEQ_AUTHOR_ID.NEXTVAL, '유시민', '17대 국회의원');

INSERT INTO AUTHOR 
VALUES (SEQ_AUTHOR_ID.NEXTVAL, '기안84', '웹툰작가');

INSERT INTO AUTHOR 
VALUES (SEQ_AUTHOR_ID.NEXTVAL, '강풀', '온라인 만화가 1세대');
COMMIT;

SELECT * FROM AUTHOR;

CREATE TABLE BOOK (
	BOOK_ID 	NUMBER(10)				,
	TITLE 		VARCHAR2(100) NOT NULL	,
	PUBS 		VARCHAR2(100)			,
	PUB_DATE 	DATE					,
	AUTHOR_ID 	NUMBER(10)				,
	PRIMARY KEY(BOOK_ID),
	CONSTRAINT C_BOOK_FK FOREIGN KEY (AUTHOR_ID)
	REFERENCES AUTHOR(AUTHOR_ID)
);

CREATE 	SEQUENCE SEQ_BOOK_ID
INCREMENT BY 	1
START WITH		1;

INSERT INTO BOOK
VALUES (SEQ_BOOK_ID.NEXTVAL, '우리들의 일그러진 영웅', '다림', '1998-02-22', 1);

INSERT INTO BOOK
VALUES (SEQ_BOOK_ID.NEXTVAL, '삼국지', '민응사', '2002-03-01', 1);

INSERT INTO BOOK
VALUES (SEQ_BOOK_ID.NEXTVAL, '토지', '마로니에북스', '2012-08-15', 2);

INSERT INTO BOOK
VALUES (SEQ_BOOK_ID.NEXTVAL, '유시민의 글쓰기 특강', '생각의 길', '2015-04-01', 3);

INSERT INTO BOOK
VALUES (SEQ_BOOK_ID.NEXTVAL, '패션왕', '중앙북스(books)', '2012-02-22', 4);

INSERT INTO BOOK
VALUES (SEQ_BOOK_ID.NEXTVAL, '26년', '재미주의', '2012-02-04', 5);
COMMIT;

SELECT	B.BOOK_ID		,
		B.TITLE			,
		B.PUBS			,
		B.PUB_DATE		,
		A.AUTHOR_ID		,
		A.AUTHOR_NAME	,
		A.AUTHOR_DESC
FROM 	BOOK	B,
		AUTHOR	A
WHERE 	B.AUTHOR_ID = A.AUTHOR_ID ;

UPDATE 	AUTHOR 
SET		AUTHOR_DESC = '서울특별시'
WHERE 	AUTHOR_NAME = '강풀'		;

DELETE 	
FROM 	AUTHOR A
WHERE 	A.AUTHOR_NAME = '기안84';

